### PR TITLE
Upgrade JCIFS dependent library to latest version, fix URL in readme

### PR DESCRIPTION
**Pull request by GregBragg**
Hi @artembilan ,

Here is a PR to update the dependent JCIFS library to the latest version and to create a new 1.2.2 Release build for the Spring Integration SMB extension library.

Thanks!
Greg.

### CODE REVIEW

**Comment by GregBragg** [comment]
Looks like this PR will resolve https://github.com/spring-projects/spring-integration-extensions/issues/249 with this change I was able to rebuilt the project with openjdk version "17.0.2" 2022-01-18 sucessfully with the latest JCIFS dependent library.

**Comment by artembilan** [comment]
Good . I will look on Monday

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-integration-extensions/commit/3bd896caed342dc47ad77b5958fc2489f512d9d4.

@GregBragg , thank you for contribution.

Please, consider the next time to keep your local project copy as up-to-date and create top-level branches for the fixed you are going to contribute.
Now your `main` branch is too dirty to apply changes back and forward.
See our Guidelines for details: https://github.com/spring-projects/spring-integration/blob/main/CONTRIBUTING.adoc

**Comment by GregBragg** [comment]
Thanks @artembilan , I realized too late my mistake... it's been awhile with this project. I'll probably have to delete my fork and start over for the next time.

Thanks again.

**Pull request closed without merging**
