### PR TITLE
INTEXT-50: Cassandra Adapter Improvements

### PR DESCRIPTION
**Pull request by artembilan**
JIRA: https://jira.spring.io/browse/INTEXT-50

### CODE REVIEW

**Comment by artembilan** [comment]
Pushed more improvements.

From my perspective it is ready to merge.

TODO for separate JIRAs:
* Namespace support for `<int-cassandra:outbound-gateway>` and `<int-cassandra:outbound-channel-adapter>`
* All other desired/required components.

Of course, we can address those already after XD release and do release this SI-Cassandra M1 as is.

**Comment by garyrussell** [comment]
Merged as 9e4c7e00db6f3f000d6709ba6385fcd2c669cb40

Polish: https://github.com/garyrussell/spring-integration/commit/e466cca59b7bee69adefaddee0cc14501d54b5f5

**Comment by garyrussell** [comment]
Closed wrong PR

**Comment by garyrussell** [comment]
Squashed, merged 2bcd54cfba6b19e9b762c09ac59225c1d9b6c95c

**Pull request closed without merging**
