### PR TITLE
INTEXT-195: Add XMPP Extension for Smack 4.1

### PR DESCRIPTION
**Pull request by artembilan**
JIRA: https://jira.spring.io/browse/INTEXT-195

### CODE REVIEW

**Comment by artembilan** [comment]
The first commit is just a copy/paste of existing code with build environment.

The second one will be for the upgrade. I let you know when it is ready for review/ to merge.

@garyrussell , please, make sure that `gradlew` is executable for Unix on merge.

Thanks.

**Comment by garyrussell** [comment]
Perhaps the package should be `o.s.integration.x.xmpp` so stack traces etc on StackOverflow will clearly show which version is being used.

**Comment by garyrussell** [comment]
You said "commit" - do you mean PR - i.e. do you want this merged, or are you adding another commit to this PR?

**Comment by artembilan** [comment]
Yes, I mean one more commit to this PR for better review.
Although you can merge if you find it as a more convenient way.

No, I don't agree for the `o.s.integration.x.xmpp`:
* from one side it would be easier for us to mere it to the Core back eventually;
* from other - don't forget that end user can configure flow using Java config or even DSL. So, with the new package he has to change all imports to one side, and after upgrade to SI-4.3 to another.

On SO we always can ask about the version for XMPP module.

**Comment by garyrussell** [comment]
:+1:

**Comment by artembilan** [comment]
Pushed

**Comment by artembilan** [comment]
Pushed

**Comment by artembilan** [comment]
Pushed.

@Flowdalic , thank you for reaching this one!
Actually I've removed that dependency at all, because our tests work as is. See the appropriate commit.

**Comment by Flowdalic** [comment]
You certainly want smack-java for all aspects of Smack to work (DNS SRV RR, Basr64, and much more). I strongly recommend to add it.

**Comment by artembilan** [comment]
Good morning/day, @Flowdalic !

I guess you mean `smack-java7`. OK, that's minor to fix...

From other side downloading the full smack distribution I see there a lot of artifacts.
Would you mind sharing with us where to read about each of them?
Yes, many of them are self-described (like `tcp` or `android`), but some of them really can be as transitive dependencies of another. 

Another my concern: when I add `smack-java7`, I see `smack-sasl-javax` as transitive dependency. From here I'm not sure that I really always need SASL...

Well, please, find the whole dependencies tree for this project:
```
+--- org.igniterealtime.smack:smack-tcp:4.1.4
|    \--- org.igniterealtime.smack:smack-core:4.1.4
|         +--- org.jxmpp:jxmpp-core:0.4.2
|         |    \--- org.jxmpp:jxmpp-util-cache:0.4.2
|         \--- xpp3:xpp3:1.1.4c
+--- org.igniterealtime.smack:smack-java7:4.1.4
|    +--- org.igniterealtime.smack:smack-core:4.1.4 (*)
|    +--- org.igniterealtime.smack:smack-resolver-javax:4.1.4
|    |    \--- org.igniterealtime.smack:smack-core:4.1.4 (*)
|    \--- org.igniterealtime.smack:smack-sasl-javax:4.1.4
|         \--- org.igniterealtime.smack:smack-core:4.1.4 (*)
+--- org.igniterealtime.smack:smack-extensions:4.1.4
|    +--- org.igniterealtime.smack:smack-core:4.1.4 (*)
|    \--- org.igniterealtime.smack:smack-im:4.1.4
|         \--- org.igniterealtime.smack:smack-core:4.1.4 (*)
```

Maybe we really can leave the provide choice for end-user as an additional artifact to his app?
At least it is our intention in other projects when we specify only those dependencies which we really need to compile. Although some of them are sometimes `optional`. And looks like this `smack-java7` should be even `runtime` dependency.

Now I run to test it against Google chat...
Come back to you soon!

**Comment by artembilan** [comment]
Ha!

I'm really facing an issue without `smack-java7`: `Base64` with `NPE` on the non-initialized `base64encoder` field. Not if it is initialized with some other alternative (instead of `smack-java7`) resolver, but that looks like bad design and doesn't help to understand what's wrong even from the StackTrace:
```
Caused by: java.lang.NullPointerException
	at org.jivesoftware.smack.util.stringencoder.Base64.encode(Base64.java:64)
	at org.jivesoftware.smack.util.stringencoder.Base64.encode(Base64.java:60)
	at org.jivesoftware.smack.util.stringencoder.Base64.encodeToString(Base64.java:42)
	at org.jivesoftware.smackx.caps.EntityCapsManager.generateVerificationString(EntityCapsManager.java:707)
	at org.jivesoftware.smackx.caps.EntityCapsManager.generateVerificationString(EntityCapsManager.java:581)
	at org.jivesoftware.smackx.caps.EntityCapsManager.updateLocalEntityCaps(EntityCapsManager.java:477)
	at org.jivesoftware.smackx.caps.EntityCapsManager.<init>(EntityCapsManager.java:309)
	at org.jivesoftware.smackx.caps.EntityCapsManager.getInstanceFor(EntityCapsManager.java:374)
	at org.jivesoftware.smackx.caps.EntityCapsManager$1.connectionCreated(EntityCapsManager.java:115)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.initConnection(XMPPTCPConnection.java:645)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:843)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:365)
	at org.springframework.integration.xmpp.config.XmppConnectionFactoryBean.start(XmppConnectionFactoryBean.java:153)
```
Well, to go ahead and stop eating time I'm adding `smack-java7` as required dependency, but you  should re-think your artifacts architecture do not waste time in the future for similar issues from the other community members.

Thank you for the support anyway!

**Comment by artembilan** [comment]
With the `smack-java7` I went a bit further. But there is something new for me:
```
WARNING: Failed to parse extension packet in Presence packet. Attributes: from=abilan@pivotal.io/gmail.2C8A271F id=null
org.jivesoftware.smack.SmackException: Caps elment with missing attributes. Attributes: hash=null version=1.1 node=http://mail.google.com/xmpp/client/caps
	at org.jivesoftware.smackx.caps.provider.CapsExtensionProvider.parse(CapsExtensionProvider.java:54)
	at org.jivesoftware.smackx.caps.provider.CapsExtensionProvider.parse(CapsExtensionProvider.java:28)
	at org.jivesoftware.smack.provider.Provider.parse(Provider.java:35)
	at org.jivesoftware.smack.util.PacketParserUtils.parseExtensionElement(PacketParserUtils.java:929)
	at org.jivesoftware.smack.util.PacketParserUtils.addExtensionElement(PacketParserUtils.java:1060)
	at org.jivesoftware.smack.util.PacketParserUtils.parsePresence(PacketParserUtils.java:583)
	at org.jivesoftware.smack.util.PacketParserUtils.parseStanza(PacketParserUtils.java:155)
	at org.jivesoftware.smack.AbstractXMPPConnection.parseAndProcessStanza(AbstractXMPPConnection.java:956)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$500(XMPPTCPConnection.java:140)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:989)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:944)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:959)
	at java.lang.Thread.run(Thread.java:745)
```

Really there is no any our line of code...

BTW, chat works well.

**Comment by artembilan** [comment]
Pushed

**Comment by Flowdalic** [comment]
> doesn't help to understand what's wrong even from the StackTrace:

Looking at the stacktrace reveals you which field is null, looking at the source shows you what would initialize it.

> but you should re-think your artifacts architecture do not waste time in the future for similar issues from the other community members.

There is really no other way around the artifact design. Smack's a multi platform library, which works on Android and Java 7. Depending on the target, you need to initialize things differently. Maybe the Smack Readme could state more clearly that you need either `smack-android` or `smack-java7`.

**Comment by artembilan** [comment]
Thank you, @Flowdalic, for coming back to me!
And for your comments as well.

Yes, README would be be good place to explain the architecture, but I suppose you should to do something with the logging message for that NPE. Something like this:

> The `base64encoder` hasn't been initialized. Consider to add `smack-android` or `smack-java7` library to your CLASSPATH depending of your platform.

@garyrussell , from my perspective nothing to do here any more.

@Flowdalic , make, please, a comment for that `WARNING` from Smack around `Presence` parsing.

**Comment by garyrussell** [comment]
Merged as 2e9247711d72959dc1a3509451bd377e34ec1c29 after README polish and whitespace fixes.

**Pull request closed without merging**
