### PR TITLE
Hazelcast: Compatibility with IO-2.0

### PR DESCRIPTION
**Pull request by artembilan**
* Add IO plugin
* Upgrade to Gradle 2.4
* Upgrade dependencies
* Upgrade to Hazelcast-3.5 and therefore make compatible with IO-2.0
* All these changes and tests make this module compatible with SI-4.2

### CODE REVIEW

**Comment by artembilan** [comment]
See spring-projects/spring-integration#1482 for more info.
Feel free to merge this one after that and fresh test against Platform with fresh SI in it to be sure that there is no any warn about deprecations.

**Comment by erenavsarogullari** [comment]
Thanks for this PR as well. The changeset looks good for me ;)

**Comment by artembilan** [comment]
@garyrussell , let me know, if I can go ahead and merge this PR, having the core PR merged.
Thanks.

**Comment by garyrussell** [comment]
Sure, go ahead and merge.

**Pull request merged**
