### PR TITLE
Fix to memory leak when closing SmbSession

### PR DESCRIPTION
**Pull request by beardy247**
Fix for issue #225

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@beardy247 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration-extensions&pullRequestId=226)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-integration-extensions&pullRequestId=226) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@beardy247 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration-extensions&pullRequestId=226)!

**Comment by beardy247** [comment]
Hold off on reviewing this for a while, I've been doing some more profiling and I don't think that I've eliminated the leak after all.

**Comment by beardy247** [comment]
Hi @artembilan ,

I'll have a look at the indents, I didn't explicitly change anything but eclipse may have mangled it.

I have now properly got to the bottom of the memory leak, jcifs.CIFSContext doesn't implement Closable but it does have a close() method. The SmbShare(SmbConfig _smbConfig, Properties _props) constructor instantiates a BaseContext implementation of CIFSContext. My fix makes sure the BaseContext is closed if it's created in the constructor.

**Pull request closed without merging**
