### PR TITLE
Fix memory leak on authentication error

### PR DESCRIPTION
**Pull request by beardy247**
I believe the root cause of this is in the jCIFS library but this mitigates the
problem.

### CODE REVIEW

**Comment by beardy247** [comment]
@GregBragg @artembilan

**Comment by beardy247** [comment]
Note: I didn't include the upgrade to jcifs-2.1.18 in this commit but that is the version that I'm using.

**Comment by GregBragg** [comment]
@beardy247 Ok thanks, looks good! You can commit the changes to upgrade the jCIFS library to the latest release which as of yesterday is jcifs-2.1.19 in the Gradle build.gradle file if you want. I'm good with the changes.

**Comment by GregBragg** [comment]
@beardy247  Actually scratch my last comment, I only see  jcifs-2.1.18 in the Maven Repository. Looks like they are only preparing to build the next release as it is not ready yet.

**Comment by beardy247** [comment]
@GregBragg I've upgraded to 2.1.18 as per your message about 2.1.19 not being in the maven repo yet. Not sure why the message isn't in the thread above.

**Comment by GregBragg** [comment]
@beardy247 yeah sorry, I deleted the message as I couldn't find the library at first in Maven, then I found it.

I reviewed the change that was made from 2.1.18 to 2.1.19 and it's not significant enough for me to ask you to retest with 2.1.19, however I'll leave that up to you if you want to make the extra effort.

The only change was this:
https://github.com/codelibs/jcifs/commit/be2dc950404d14af828b14036211d9447146e324
so not sure if that makes any difference in what you were seeing with the memory leaks.

**Comment by GregBragg** [comment]
I don't think it would hurt Artem. The way that the URLStreamHandler was instantiated before in version 2.1.18 was suspect anyways, I like the fix they did from 2.1.18 to 2.1.19, so I think we should go with the latest build which only came out yesterday.

**Comment by beardy247** [comment]
I've tested with 2.1.19 and the change is inconsequential to our usage.

**Comment by GregBragg** [comment]
@beardy247 Thanks a bunch!

**Comment by beardy247** [comment]
I've got some additional stuff to contribute in the future, I've written a DSL wrapper for the  SmbInboundFileSynchronizer and a SmbLastModifiedFileListFilter. I can't submit them yet though as I haven't had change to write unit tests for them. When I find some time I'll get the tests written and a pull request sorted.

**Comment by artembilan** [comment]
@beardy247 , @GregBragg ,

`spring-integration-smb-1.2.1.RELEASE` is on its way to Maven Central.

**Pull request merged**
