### PR TITLE
GH-173: Leaders: Warn event errors, not re-throw

### PR DESCRIPTION
**Pull request by artembilan**
Fixes GH-173 (https://github.com/spring-projects/spring-integration-extensions/issues/173)

Currently when an error is thrown from the event publishing the role granting is broken and we just go to the role revoking.

* Since it's just an event publishing it shouldn't effect the original leader election.
* `try...catch` event publishing in the `LeaderInitiator` and `logger.warn` an `Exception`

### CODE REVIEW

**Comment by artembilan** [comment]
@garyrussell , 

I'm pretty sure that we should port the solution to other `LeaderInitiator` implementations: https://jira.spring.io/browse/INT-4220

**Comment by garyrussell** [comment]
I am not sure that this is the right answer on the grant side; if the application fails to process the leader onGranted event, shouldn't we yield leadership? On the revoked side it might be less of a problem because the app might still think it's leader, but I suppose there's not much more we can do than log the exception.

**Comment by artembilan** [comment]
Why? It is just an event.
One of the listeners may process it properly, but another fail by some its own state.

For the strong leadership we require `Candidate`. The `LeaderEventPublisher` is optional for the `LeaderInitiator` anyway...

**Comment by garyrussell** [comment]
Oh, yeah, I missed that - I forgot that leadership events are simply application event.

**Pull request merged**
